### ISSUE TITLE
JS Behat tests failing due to session or auth issue (selenium & chromedriver)

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/PluginSkeleton#138] opened 2018-11-13 10:06 UTC
Hi, guys.

It looks like JS behat tests failing due to some session or auth issue:

```bash
$ vendor/bin/behat 
@managing_products
...
  @ui @javascript
  Scenario: Adding a text attribute to product
    Given I want to create a new simple product
      Expected to be on "http://localhost:8080/admin/products/new/simple" but found "http://localhost:8080/admin/login" instead (Sylius\Behat\Page\UnexpectedPageException)
```

PS: I've followed all installation steps for clean copy of latest plugin skeleton. Chromedriver and selenium server also latest.

Also, how about adding it to travis and add badges? As I can see - config is ready for that.
Thanks

**Comment by bitbager** [comment] 2018-11-13 16:45
@pamil, I guess it's similar to what we've been talking about regarding this thread: https://forum.sylius.com/t/behat-javascript-scenarios-can-t-be-logged-as-admin/618

**Comment by igormukhingmailcom** [comment] 2018-11-13 17:29
I'm also running it on OSX (if this matters).

**Comment by Zales0123** [comment] 2018-11-14 11:37
I believe there can be something with resolving `.env` files for the plugin application... I've managed to make it work, but I was also getting this error at the beginning. The problem was, the server I had run was using different `env` than Behat tests. Could you please try to run `set -a && source tests/Application/.env.test && set +a`? It **can** solve the problem, but still, it's questionable should we require such a step or should it be resolved automatically.

**Comment by igormukhingmailcom** [comment] 2018-11-14 15:34
Thank you a lot about idea, @Zales0123 

I think the solution will be copying `tests/Application/.env.test` to `tests/Application/.env` rather than sourcing it. That is because `server:run` command gets `.env` or `.env.dist` be default regardless what was provided at `--env=` option (and I'm wondering why it designed like that).

Will check this soon.

**Comment by igormukhingmailcom** [comment] 2018-11-15 10:28
Just checked.
Yeah. Executing `cp tests/Application/.env.test.dist tests/Application/.env` before `vendor/bin/behat --tags="@javascript"` make it works.

**Comment by Zales0123** [comment] 2018-11-15 10:31
👍 could you please open a PR with installation instruction update? We will think about how to solve it in a better way, but for now it would be better than nothing :)

**Comment by igormukhingmailcom** [comment] 2018-11-15 10:40
I've found a way how to fix that without any changes in workflow. We just should fix `bin/console` to take env from input parameter. See reference to `0d8c117` above.

**Comment by pamil** [comment] 2020-06-03 12:26
It looks like an issue caused by @FriendsOfBehat SymfonyExtension v1, could you open a new issue if it still exists with v2?

**Closed by pamil** 2020-06-03 12:26 UTC
Labels: Potential Bug
